const jobTitles = [
        "Software Engineer",
        "Frontend Developer",
        "Backend Developer",
        "Full Stack Developer",
        "UI/UX Designer",
        "Product Manager",
        "Project Manager",
        "DevOps Engineer",
        "Data Scientist",
        "Data Analyst",
        "Machine Learning Engineer",
        "Mobile App Developer",
        "Web Developer",
        "Graphic Designer",
        "Quality Assurance Engineer",
        "System Administrator",
        "Cloud Architect",
        "Technical Support Engineer",
        "Business Analyst",
        "IT Manager",
        "Network Engineer",
        "Cybersecurity Analyst",
        "Database Administrator",
        "Digital Marketing Specialist",
        "SEO Specialist",
        "Content Strategist",
        "Social Media Manager",
        "Technical Writer",
        "HR Manager",
        "Recruiter",
        "Sales Manager",
        "Account Manager",
        "Customer Success Manager",
        "Financial Analyst",
        "Marketing Manager",
        "Operations Manager",
        "Legal Advisor",
        "Software Tester",
        "Automation Engineer",
        "Blockchain Developer",
        "AR/VR Developer",
        "Embedded Systems Engineer",
        "Game Developer",
        "Teacher",
        "Doctor",
        "Other"
      ];
export default jobTitles;