const jobTitles = [
  { value: "Software Engineer", label: "Software Engineer" },
  { value: "Frontend Developer", label: "Frontend Developer",},
  { value: "Backend Developer", label: "Backend Developer"},
  { value: "Full Stack Developer", label: "Full Stack Developer"},
  { value: "UI/UX Designer", label: "UI/UX Designer",},
  { value: "Product Manager", label:  "Product Manager",},
  { value: "DevOps Engineer",label:   "DevOps Engineer",},
  { value: "Data Scientist", label: "Data Scientist"},
  { value: "Data Analyst", label: " Data Analyst"},
  { value: "Machine Learning Engineer", label: "Machine Learning Engineer"},
  { value: "Mobile App Developer", label: "Mobile App Developer"},
  { value: "Web Developer", label: "Web Developer"},
  { value: "Graphic Designer", label: "Graphic Designer"},
  { value: "Quality Assurance Engineerr", label: "Quality Assurance Engineer"},
  { value: "System Administrator", label:  "System Administrator"},
  { value: "Cloud Architect", label: "Cloud Architect"},
  { value: "Technical Support Engineer", label: "Technical Support Engineer"},
  { value: "Business Analyst", label:  "Business Analyst"},
  { value: "IT Manager", label: "IT Manager"},
  { value: "Network Engineer", label: "Network Engineer"},
  { value: "Cybersecurity Analyst", label: "Cybersecurity Analyst"},
  { value: "Database Administrator", label: "Database Administrator"},
  { value: "Digital Marketing Specialist", label: "Digital Marketing Specialist"},
  { value: "SEO Specialist", label:  "SEO Specialist"},
  { value: "Content Strategist", label:  "Content Strategist"},
  { value: "Social Media Manager", label:   "Social Media Manager"},
  { value: "Technical Writer", label:  "Technical Writer"},
  { value: "HR Manager", label:  "HR Manager"},
  { value: "Recruiter", label:   "Recruiter"},
  { value: "Sales Manager", label: "Sales Manager"},
  { value: "Account Manager", label:  "Account Manager"},
  { value: "Customer Success Manager", label: "Customer Success Manager"},
  { value: "Financial Analyst", label:  "Financial Analyst"},
  { value: "Marketing Manager", label:  "Marketing Manager"},
  { value: "Operations Manager", label:   "Operations Manager"},
  { value: "Legal Advisor", label:   "Legal Advisor"},
  { value: "Software Tester", label:    "Software Tester"},
  { value: "Automation Engineer", label:  "Automation Engineer"},
  { value: "Blockchain Developer", label:  "Blockchain Developer"},
  { value: "AR/VR Developer", label: "AR/VR Developer"},
  { value: "Embedded Systems Engineer", label: "Embedded Systems Engineer"},
  { value: "Game Developer", label:  "Game Developer"},
  { value: "Teacher", label:   "Teacher"},
  { value: "Doctor", label:  "Doctor"},
  { value: "Other", label:  "Other"},
];
export default jobTitles;